import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '@/shared/ui/styles/globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans-inter' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={inter.variable}>
      <body>{children}</body>
    </html>
  );
}
