import type { Metadata } from 'next';

import { fontSans } from '@/bootstrap/font';
import { ThemeProvider } from '@/bootstrap/theme-provider';

import '@/shared/ui/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={fontSans.variable} suppressHydrationWarning>
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
