import type { Metadata } from 'next';

import { fontSans } from '@/bootstrap/font';
import { RootProvider } from '@/bootstrap/providers/root-provider';

import { routing } from '@/shared/config/i18n/routing';
import '@/shared/ui/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// why: prerenders one route per locale at build time, which is what §4 requires
// of every page. Paired with dynamicParams below, an unknown locale is a 404
// instead of an on-demand render (D-110).
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export const dynamicParams = false;

export default async function RootLayout({ children, params }: LayoutProps<'/[locale]'>) {
  const { locale } = await params;

  return (
    <html lang={locale} className={fontSans.variable} suppressHydrationWarning>
      <body>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
